# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


#  bundle exec jekyll serve --livereload




# Site Settings
title: Bre@kTheLoop
# email: your-email@example.com
description: >-
  Bre@kTheLoop, GCETTS is a community of coding and CompSci enthusiasts 
  who believes in open learning and sharing knowledge.
baseurl: ""
url: "https://btl-gcetts.github.io"
cdn: "https://m1-btlcdn.netlify.app"
github_username:  btl-gcetts
email: breaktheloop01@gmail.com




# Build Settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dockerfile
  - script/
  